msrv = "1.82"

[lints]
warn = ["clippy::pedantic"]

allow = [
    "clippy::enum_variant_names",
    "clippy::vec_init_then_push",
    "clippy::needless_return",
    "clippy::manual_range_contains",
    "clippy::match_bool",
    "clippy::collapsible_else_if",
    "clippy::map_flatten",
    "clippy::filter_map_next",
    "clippy::manual_flatten",
    "clippy::needless_borrow",
    "clippy::needless_pass_by_value",
    "clippy::redundant_clone",
    "clippy::single_match",
    "clippy::upper_case_acronyms"
]
